### ISSUE TITLE
Update to use new player list API

### ISSUE THREAD

**Issue by colacadstink** [Czyryca/HVZ-Text-Alerts#11]
https://umbchvz.com/api/longGamePlayerList.php

You should probably be calling this instead of scraping the player list. :)

**Comment by colacadstink** [comment]
For testing purposes, you can specify the game ID like so:

https://umbchvz.com/api/longGamePlayerList.php?gameID=LG0000f

If you don't specify an ID, it'll use whatever game is currently in progress. This returns a JSON dictionary, where the keys are the player names and the values are their states. 

As an aside - I LOVE what you've done here. This is exactly what I made when I started playing HvZ, and it makes my heart swell to see someone else remake my code - but this time, for the website I made (and for a messaging service that I really wish I had access to back when I first did this!!). Thank you. :+1:

**Comment by Czyryca** [comment]
Neat. The API is much easier to use and let me cut a bunch of dependencies. Thanks for letting me know it exists. I've created a new branch that uses the API. I'll merge it with master if my work proves to be stable in the next weeklong.
https://github.com/Czyryca/HVZ-Text-Alerts/tree/API-working

Are there any other parameters beside gameID or any other APIs I should know about? In particular, I'd like a way to get the number of unrevealed OZs, because I don't know a good way to get that without going back to scraping the site. I see that api/meetingStats.php exists, but it looks like it's used for getting attendance, even though it looks similar to the summary line on the player list during weeklongs. Is that right?

Thanks for your contributions to the club. I don't know how we'd survive without you.

**Comment by colacadstink** [comment]
Currently, there's no other API endpoints that are relevant to your stuff. But if you want to look around, https://umbchvz.com/api/ is a listable directory, and I'm very open to suggestions if you've got feature requests!

I could easily add the player counts into this endpoint, making something that looks like this:

```
{
	"humans": 0,
	"zombies": 27,
	"ozs": 2,
	"players": {
		"name": "state"
	}
}
```

If that'd help, I can make the tweak in the next day or so and let you know once it's up.

**Comment by Czyryca** [comment]
Sure, I'd appreciate the player counts. No need to rush to add it; the next weeklong is a month away.

**Comment by colacadstink** [comment]
The API now returns JSON that looks like what I described above.
